### ISSUE TITLE
Ios pod install problem

### ISSUE THREAD

**Issue by HnjFlutter** [AppLovin/AppLovin-MAX-Flutter#10]
-> Installing AppLovinSDK (11.4.2)
      > Copying AppLovinSDK from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/AppLovinSDK/11.4.2-119a0` to `Pods/AppLovinSDK`

    -> Installing FBAudienceNetwork (6.9.0)
      > Copying FBAudienceNetwork from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/FBAudienceNetwork/6.9.0-83096` to `Pods/FBAudienceNetwork`

    -> Installing FMDB (2.7.5)
      > Copying FMDB from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/FMDB/2.7.5-2ce00` to `Pods/FMDB`

    -> Installing Firebase (8.15.0)
      > Copying Firebase from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/Firebase/8.15.0-5f819` to `Pods/Firebase`

    -> Installing FirebaseCore (8.15.0)
      > Copying FirebaseCore from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/FirebaseCore/8.15.0-5743c` to `Pods/FirebaseCore`

    -> Installing FirebaseCoreDiagnostics (8.15.0)
      > Copying FirebaseCoreDiagnostics from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/FirebaseCoreDiagnostics/8.15.0-92e07` to `Pods/FirebaseCoreDiagnostics`

    -> Installing Flutter (1.0.0)

    -> Installing Google-Mobile-Ads-SDK (8.13.0)
      > Copying Google-Mobile-Ads-SDK from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/Google-Mobile-Ads-SDK/8.13.0-05e5d` to `Pods/Google-Mobile-Ads-SDK`

    -> Installing GoogleAppMeasurement (8.15.0)
      > Copying GoogleAppMeasurement from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/GoogleAppMeasurement/8.15.0-4c19f` to `Pods/GoogleAppMeasurement`

    -> Installing GoogleDataTransport (9.1.4)
      > Copying GoogleDataTransport from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/GoogleDataTransport/9.1.4-5fffe` to `Pods/GoogleDataTransport`

    -> Installing GoogleUserMessagingPlatform (2.0.0)
      > Copying GoogleUserMessagingPlatform from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/GoogleUserMessagingPlatform/2.0.0-ab890` to `Pods/GoogleUserMessagingPlatform`

    -> Installing GoogleUtilities (7.7.0)
      > Copying GoogleUtilities from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/GoogleUtilities/7.7.0-e0913` to `Pods/GoogleUtilities`

    -> Installing PromisesObjC (2.1.1)
      > Copying PromisesObjC from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/PromisesObjC/2.1.1-ab77f` to `Pods/PromisesObjC`

    -> Installing Reachability (3.2)
      > Copying Reachability from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/Reachability/3.2-33e18` to `Pods/Reachability`

    -> Installing Toast (4.0.0)
      > Copying Toast from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/Toast/4.0.0-91b39` to `Pods/Toast`

    -> Installing applovin_max (1.0.3)

    -> Installing connectivity (0.0.1)

    -> Installing facebook_audience_network (0.0.1)

    -> Installing firebase_core (1.17.0)

    -> Installing flutter_custom_tabs (0.0.1)

    -> Installing flutter_fgbg (0.0.1)

    -> Installing fluttertoast (0.0.2)

    -> Installing google_mobile_ads (0.0.1)

    -> Installing in_app_review (0.2.0)

    -> Installing nanopb (2.30908.0)
      > Copying nanopb from `/Users/macc/Library/Caches/CocoaPods/Pods/Release/nanopb/2.30908.0-a0ba3` to `Pods/nanopb`

    -> Installing path_provider_ios (0.0.1)

    -> Installing share (0.0.1)

    -> Installing sqflite (0.0.2)

    -> Installing url_launcher_ios (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/macc/StudioProjects/test1/ios/Pods/AppLovinSDK/applovin-ios-sdk-11.4.2/AppLovinSDK.xcframework)

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:84:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:597:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:163:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 8.

**Comment by medalawi** [comment]
@HnjFlutter  
go to your project folder then find pod file then Open  it
# Uncomment the next line to define a global platform for your project

# platform :ios, '9.0' 
to
platform :ios, '10.0' 
save it then open Terminal  set  it on this path  :
cd  Your_Project_Name/ios 

then run this command
pod install --repo-update
after that if every thing is ok  Run 
flutter pub get
then
flutter run

**Comment by quanliangswift** [comment]
add  "s.static_framework = true"   in applovin_max.podspec

if remove  "use_frameworks!" in swift project, some new bugs will be occurs for other pod

**Comment by thomasmso** [comment]
https://github.com/AppLovin/AppLovin-MAX-Flutter/pull/17/files

**Comment by thomasmso** [comment]
v1.0.6 is live - feel free to give it a try

https://github.com/AppLovin/AppLovin-MAX-Flutter/releases/tag/release_1_0_6
