### ISSUE TITLE
Reward Ad Application attempted to call on a destroyed WebView

### ISSUE THREAD

**Issue by TimmyHung** [AppLovin/AppLovin-MAX-Flutter#139]
### MAX Plugin Version

3.3.0

### Flutter Version

3.1.5

### Device/Platform Info

Android 14, Pixel 6 Pro API34

### Current Behavior

I have create a widget to display Reward Ad and I have see`[MaxRewardedAd] Created new MaxRewardedAd (MaxRewardedAd{adUnitId='xxxxxxxxxxx', adListener=null, revenueListener=null, requestListenernull, adReviewListenernull, isReady=false})` shows up in my output console, but the rewarded ads don't show up.

I'm pretty sure this is a bug, I've seen rewarded ads show up normally, albeit only once.
Every time I call the rewarded ads widget and then hot reload my app, I see the error message below.

I guess reward ad use webview to display ads.
```
Application attempted to call on a destroyed WebView
W/cr_AwContents(10923): java.lang.Throwable
W/cr_AwContents(10923): 	at org.chromium.android_webview.AwContents.m(chromium-TrichromeWebViewGoogle6432.apk-stable-567263637:10)
W/cr_AwContents(10923): 	at Qb.loadingStateChanged(chromium-TrichromeWebViewGoogle6432.apk-stable-567263637:4)
W/cr_AwContents(10923): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/cr_AwContents(10923): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/cr_AwContents(10923): 	at android.os.Looper.loopOnce(Looper.java:162)
W/cr_AwContents(10923): 	at android.os.Looper.loop(Looper.java:294)
W/cr_AwContents(10923): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
W/cr_AwContents(10923): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents(10923): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
W/cr_AwContents(10923): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### Expected Behavior

Reward ad display normally.

### How to Reproduce

I use `showDialog` to call out the reward ad widget.
```dart
showDialog(context: context, builder: (BuildContext context) {
                    return Applovin_StorePageRewardAdWidget);
                    });
```
```dart
class Applovin_StorePageRewardAdWidgetState extends State<Applovin_StorePageRewardAdWidget> {
  var _rewardedAdRetryAttempt = 0;
  int second = 0;

  @override
  void initState() {
    super.initState();
    initializeRewardedAd();
    startAd();
  }

  @override
  void dispose() {
    super.dispose();
  }

  void startAd()async{
    if((await AppLovinMAX.isRewardedAdReady(AppLovinHelper.StorePage_RewardAdUnitID))!){
      print("start ad");
      AppLovinMAX.showRewardedAd(AppLovinHelper.StorePage_RewardAdUnitID);
    }else{
      print("Wait for ${++second} sec");
      await Future.delayed(Duration(seconds: 1));
      startAd();
    }
  }

  void initializeRewardedAd() {
    print("initialize Applovin Reward Ad");
    try{
    AppLovinMAX.setRewardedAdListener(RewardedAdListener(
      onAdLoadedCallback: (ad) {
        // Rewarded ad is ready to be shown. AppLovinMAX.isRewardedAdReady(_rewarded_ad_unit_id) will now return 'true'
        print('Rewarded ad loaded from ' + ad.networkName);
        // Reset retry attempt
        _rewardedAdRetryAttempt = 0;
    }, onAdLoadFailedCallback: (adUnitId, error) {
        _rewardedAdRetryAttempt = _rewardedAdRetryAttempt + 1;

       int retryDelay = pow(2, min(6, _rewardedAdRetryAttempt)).toInt();
       print('Rewarded ad failed to load with code ' + error.code.toString() + ' - retrying in ' + retryDelay.toString() + 's');

        Future.delayed(Duration(milliseconds: retryDelay * 1000), () {
            AppLovinMAX.loadRewardedAd(AppLovinHelper.StorePage_RewardAdUnitID);
        });
    }, onAdDisplayedCallback: (ad) {
      print("a");
    }, onAdDisplayFailedCallback: (ad, error) {
      print("B");
    }, onAdClickedCallback: (ad) {
      print("C");
    }, onAdHiddenCallback: (ad) {
      print("D");
    }, onAdReceivedRewardCallback: (ad, reward) {
      print("e");
    }));
    }catch(Exception){
      print("Applovin Reward Ad initialize failed");
    }
}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
            body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                CircularProgressIndicator(color: Theme.of(context).primaryColor),
                SizedBox(height: 10),
                Text("Ad loading...",style: TextStyle(color: Colors.white, fontSize: 20))
              ],
            ),
          ),
    );
  }
}
```

**Comment by applovinAsh** [comment]
@TimmyHung , please provide the verbose logs so we can get a better understanding of what is going on. To enable verbose logs, see here: https://support.applovin.com/hc/en-us/articles/4413218413325-How-to-Enable-Verbose-Logging-in-the-AppLovin-SDK. 

If you would like to provide the logs in a zendesk ticket instead, please open a ticket here: https://support.applovin.com/hc/en-us/requests/new
