### ISSUE TITLE
"onAdLoadFailedCallback" method not  call.

### ISSUE THREAD

**Issue by haianhsing** [AppLovin/AppLovin-MAX-Flutter#60]
### MAX Plugin Version

11.5.5

### Flutter Version

2.3.1

### Device/Platform Info

all

### Current Behavior

"onAdLoadFailedCallback" method not  call.
When load again, log "An ad is already loading".

### Expected Behavior

"onAdLoadFailedCallback" method call.

### How to Reproduce

load ad without network.

**Comment by thomasmso** [comment]
This is expected behaviour, and eventually the "ad load failure" callback will fire.

**Comment by thomasmso** [comment]
"ad load failure" is that callback. If you enable and send over the verbose logs we can check it out.

**Comment by haianhsing** [comment]
This is my code :
 ```
import 'package:applovin_max/applovin_max.dart';

class Max {
  static Future init(String sdkKey) async {
    await AppLovinMAX.initialize(sdkKey);
  }
}

import 'package:ad/ad.dart';
import 'package:applovin_max/applovin_max.dart' hide MaxAd, MaxError;

class InterstitialAd {
  static Function(MaxAd ad)? _onAdDisplayedCallback;
  static Function(MaxAd, MaxError error)? _onAdDisplayFailedCallback;
  static Function(MaxAd ad)? _onAdClickedCallback;
  static Function(MaxAd ad)? _onAdHiddenCallback;
  static Function(MaxAd ad)? _onAdRevenuePaidCallback;

  static void loadAd(
    String unitId, {
    Function(MaxAd ad)? onAdLoadedCallback,
    Function(String adUnitId, MaxError error)? onAdLoadFailedCallback,
  }) {
    AppLovinMAX.setInterstitialListener(
      InterstitialListener(
        onAdLoadedCallback: (ad) {
          LogUtils.d('onAdLoadedCallback: $ad');
          onAdLoadedCallback?.call(MaxAd(ad.adUnitId, ad.networkName,
              ad.revenue, ad.creativeId, ad.dspName, ad.placement));
        },
        onAdLoadFailedCallback: (adUnitId, error) {
          LogUtils.d('onAdLoadFailedCallback: $error');
          onAdLoadFailedCallback?.call(
              adUnitId, MaxError(error.code, error.message));
        },
        onAdDisplayedCallback: (ad) {
          LogUtils.d('onAdDisplayedCallback: $ad');
          _onAdDisplayedCallback?.call(MaxAd(ad.adUnitId, ad.networkName,
              ad.revenue, ad.creativeId, ad.dspName, ad.placement));
        },
        onAdDisplayFailedCallback: (ad, error) {
          LogUtils.d('onAdDisplayFailedCallback: $ad, $error');
          _onAdDisplayFailedCallback?.call(
              MaxAd(ad.adUnitId, ad.networkName, ad.revenue, ad.creativeId,
                  ad.dspName, ad.placement),
              MaxError(error.code, error.message));
        },
        onAdClickedCallback: (ad) {
          LogUtils.d('onAdClickedCallback: $ad');
          _onAdClickedCallback?.call(MaxAd(ad.adUnitId, ad.networkName,
              ad.revenue, ad.creativeId, ad.dspName, ad.placement));
        },
        onAdHiddenCallback: (ad) {
          LogUtils.d('onAdHiddenCallback: $ad');
          _onAdHiddenCallback?.call(MaxAd(ad.adUnitId, ad.networkName,
              ad.revenue, ad.creativeId, ad.dspName, ad.placement));
        },
        onAdRevenuePaidCallback: (ad) {
          LogUtils.d('onAdRevenuePaidCallback: $ad');
          _onAdRevenuePaidCallback?.call(MaxAd(ad.adUnitId, ad.networkName,
              ad.revenue, ad.creativeId, ad.dspName, ad.placement));
        },
      ),
    );
    AppLovinMAX.loadInterstitial(unitId);
  }

  static void showAd(
    String unitId, {
    Function(MaxAd ad)? onAdDisplayedCallback,
    Function(MaxAd ad, MaxError error)? onAdDisplayFailedCallback,
    Function(MaxAd ad)? onAdClickedCallback,
    Function(MaxAd ad)? onAdHiddenCallback,
    Function(MaxAd ad)? onAdRevenuePaidCallback,
  }) async {
    _onAdDisplayedCallback = onAdDisplayedCallback;
    _onAdDisplayFailedCallback = onAdDisplayFailedCallback;
    _onAdClickedCallback = onAdClickedCallback;
    _onAdHiddenCallback = onAdHiddenCallback;
    _onAdRevenuePaidCallback = onAdRevenuePaidCallback;
    if (await isAdLoaded(unitId) == true) {
      AppLovinMAX.showInterstitial(unitId);
    } else {
      loadAd(unitId);
    }
  }

  static Future<bool?> isAdLoaded(String unitId) async {
    return await AppLovinMAX.isInterstitialReady(unitId);
  }
}

await Max.init(
     'Ehm2XimbDDeeE4URXGM6zhJ19ON5Pzt4b9a3eLLwsvFtLcyuQeciyfQ76amrDwebOSDmWT727gzBnO8Sufi2sJ');
InterstitialAd.loadAd('46fe756b433568d6')
```

This is all the log :
```
2022-12-07 16:07:23.060   833-833   JustTrustMe             fate.facefilter.palmistry            D  Hooking DefaultHTTPClient for: fate.facefilter.palmistry
2022-12-07 16:07:23.062   833-833   EdXposed-Bridge         fate.facefilter.palmistry            E  java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient;
                                                                                                    	at just.trust.me.Main.handleLoadPackage(Main.java:67)
                                                                                                    	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
                                                                                                    	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
                                                                                                    	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
                                                                                                    	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:61)
                                                                                                    	at de.robv.android.xposed.MethodHooker.handleHookedMethod(MethodHooker.java:94)
                                                                                                    	at EdHooker_d80f73e34da17c301b40feab7995d5a6a0b56621.hook(Unknown Source:45)
                                                                                                    	at android.app.LoadedApk.getResources(LoadedApk.java:1188)
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:2462)
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:2454)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6343)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at de.robv.android.xposed.MethodHooker.handleHookedMethod(MethodHooker.java:81)
                                                                                                    	at EdHooker_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:48)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.DefaultHttpClient" on path: DexPathList[[zip file "/data/app/just.trust.me-KiFVHacJw-jqtjCObz0FFA==/base.apk"],nativeLibraryDirectories=[/system/lib64, /product/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at just.trust.me.Main.handleLoadPackage(Main.java:67) 
                                                                                                    	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37) 
                                                                                                    	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61) 
                                                                                                    	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117) 
                                                                                                    	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:61) 
                                                                                                    	at de.robv.android.xposed.MethodHooker.handleHookedMethod(MethodHooker.java:94) 
                                                                                                    	at EdHooker_d80f73e34da17c301b40feab7995d5a6a0b56621.hook(Unknown Source:45) 
                                                                                                    	at android.app.LoadedApk.getResources(LoadedApk.java:1188) 
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:2462) 
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:2454) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6343) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at de.robv.android.xposed.MethodHooker.handleHookedMethod(MethodHooker.java:81) 
                                                                                                    	at EdHooker_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:48) 
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:214) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2022-12-07 16:07:23.080   833-833   MultiDex                fate.facefilter.palmistry            I  VM with version 2.1.0 has multidex support
2022-12-07 16:07:23.080   833-833   MultiDex                fate.facefilter.palmistry            I  Installing application
2022-12-07 16:07:23.080   833-833   MultiDex                fate.facefilter.palmistry            I  VM has multidex support, MultiDex support library is disabled.
2022-12-07 16:07:23.094   833-833   AppLovinSdk             fate.facefilter.palmistry            D  [AppLovinSdk] Java version 8 supported.
2022-12-07 16:07:23.095   833-833   AppLovinSdk             fate.facefilter.palmistry            D  [AppLovinSdk] Attaching Activity lifecycle manager...
2022-12-07 16:07:23.101   833-833   WM-WrkMgrInitializer    fate.facefilter.palmistry            D  Initializing WorkManager with default configuration.
2022-12-07 16:07:23.119   833-883   ilter.palmistr          fate.facefilter.palmistry            I  The ClassLoaderContext is a special shared library.
2022-12-07 16:07:23.124   833-883   chatty                  fate.facefilter.palmistry            I  uid=11880(fate.facefilter.palmistry) Thread-4 identical 1 line
2022-12-07 16:07:23.129   833-883   ilter.palmistr          fate.facefilter.palmistry            I  The ClassLoaderContext is a special shared library.
2022-12-07 16:07:23.211   833-895   ResourceExtractor       fate.facefilter.palmistry            I  Resource version mismatch res_timestamp-1-1670400441959
2022-12-07 16:07:23.219   833-896   DynamiteModule          fate.facefilter.palmistry            W  Local module descriptor class for com.google.android.gms.measurement.dynamite not found.
2022-12-07 16:07:23.229   833-883   DynamiteModule          fate.facefilter.palmistry            I  Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:224400003
2022-12-07 16:07:23.229   833-883   DynamiteModule          fate.facefilter.palmistry            I  Selected remote version of com.google.android.gms.ads.dynamite, version >= 224400003
2022-12-07 16:07:23.229   833-883   DynamiteModule          fate.facefilter.palmistry            V  Dynamite loader version >= 2, using loadModule2NoCrashUtils
2022-12-07 16:07:23.233   833-896   DynamiteModule          fate.facefilter.palmistry            I  Considering local module com.google.android.gms.measurement.dynamite:0 and remote module com.google.android.gms.measurement.dynamite:87
2022-12-07 16:07:23.233   833-896   DynamiteModule          fate.facefilter.palmistry            I  Selected remote version of com.google.android.gms.measurement.dynamite, version >= 87
2022-12-07 16:07:23.233   833-896   DynamiteModule          fate.facefilter.palmistry            V  Dynamite loader version >= 2, using loadModule2NoCrashUtils
2022-12-07 16:07:23.238   833-896   System                  fate.facefilter.palmistry            W  ClassLoader referenced unknown path: 
2022-12-07 16:07:23.260   833-883   ilter.palmistr          fate.facefilter.palmistry            W  ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk*3181387750:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes2.dex*3802605069:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes3.dex*2074135178:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes4.dex*1923087036:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes5.dex*632453550:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes6.dex*3601629457:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes7.dex*4020068137])
2022-12-07 16:07:23.262   833-883   ilter.palmistr          fate.facefilter.palmistry            W  Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/00000123/dl-AdsFdrDynamite.integ_224400003100000.apk
2022-12-07 16:07:23.262   833-883   ilter.palmistr          fate.facefilter.palmistry            W  NOTE: This wastes RAM and hurts startup performance.
2022-12-07 16:07:23.262   833-883   ilter.palmistr          fate.facefilter.palmistry            W  Found duplicated class when checking oat files: 'Landroid/support/v4/app/RemoteActionCompatParcelizer;' in /data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk and /data/user_de/0/com.google.android.gms/app_chimera/m/00000123/dl-AdsFdrDynamite.integ_224400003100000.apk
2022-12-07 16:07:23.262   833-883   ilter.palmistr          fate.facefilter.palmistry            W  
2022-12-07 16:07:23.338   833-896   ilter.palmistr          fate.facefilter.palmistry            W  ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk*3181387750:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes2.dex*3802605069:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes3.dex*2074135178:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes4.dex*1923087036:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes5.dex*632453550:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes6.dex*3601629457:/data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk!classes7.dex*4020068137])
2022-12-07 16:07:23.339   833-896   ilter.palmistr          fate.facefilter.palmistry            W  Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/00000122/MeasurementDynamite.apk
2022-12-07 16:07:23.339   833-896   ilter.palmistr          fate.facefilter.palmistry            W  NOTE: This wastes RAM and hurts startup performance.
2022-12-07 16:07:23.339   833-896   ilter.palmistr          fate.facefilter.palmistry            W  Found duplicated class when checking oat files: 'Landroid/support/v4/app/RemoteActionCompatParcelizer;' in /data/app/fate.facefilter.palmistry-WFzEZnSl3pZmEu7JZJwsdQ==/base.apk and /data/user_de/0/com.google.android.gms/app_chimera/m/00000122/MeasurementDynamite.apk
2022-12-07 16:07:23.339   833-896   ilter.palmistr          fate.facefilter.palmistry            W  
2022-12-07 16:07:23.367   833-896   DynamiteModule          fate.facefilter.palmistry            W  Local module descriptor class for com.google.android.gms.measurement.dynamite not found.
2022-12-07 16:07:23.373   833-900   NetworkSecurityConfig   fate.facefilter.palmistry            D  No Network Security Config specified, using platform default
2022-12-07 16:07:23.427   833-895   ResourceExtractor       fate.facefilter.palmistry            I  Extracted baseline resource assets/flutter_assets/kernel_blob.bin
2022-12-07 16:07:23.428   833-895   ResourceExtractor       fate.facefilter.palmistry            I  Extracted baseline resource assets/flutter_assets/vm_snapshot_data
2022-12-07 16:07:23.450   833-905   FA-Ads                  fate.facefilter.palmistry            I  App measurement initialized, version: 75031
2022-12-07 16:07:23.450   833-905   FA-Ads                  fate.facefilter.palmistry            I  To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
2022-12-07 16:07:23.466   833-895   ResourceExtractor       fate.facefilter.palmistry            I  Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
2022-12-07 16:07:23.472   833-833   ilter.palmistry         fate.facefilter.palmistry            W  type=1400 audit(0.0:32326): avc: denied { read } for name="max_map_count" dev="proc" ino=11494894 scontext=u:r:untrusted_app:s0:c88,c263,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0
2022-12-07 16:07:23.482   833-833   AdrenoGLES              fate.facefilter.palmistry            I  QUALCOMM build                   : ba734b1, I0a3e8c4129
                                                                                                    Build Date                       : 11/08/19
                                                                                                    OpenGL ES Shader Compiler Version: EV031.27.05.02
                                                                                                    Local Branch                     : 
                                                                                                    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.8.9.C1.08.00.00.516.287
                                                                                                    Remote Branch                    : NONE
                                                                                                    Reconstruct Branch               : NOTHING
2022-12-07 16:07:23.482   833-833   AdrenoGLES              fate.facefilter.palmistry            I  Build Config                     : S P 8.0.11 AArch64
2022-12-07 16:07:23.487   833-833   AdrenoGLES              fate.facefilter.palmistry            I  PFP: 0x016ee183, ME: 0x00000000
2022-12-07 16:07:23.620   833-928   flutter                 fate.facefilter.palmistry            I  The Dart VM service is listening on http://127.0.0.1:38951/cRQizaLCe1Y=/
2022-12-07 16:07:23.631   833-905   FA-Ads                  fate.facefilter.palmistry            I  Tag Manager is not found and thus will not be used
2022-12-07 16:07:23.695   833-905   FA-Ads                  fate.facefilter.palmistry            W  Analytics storage consent denied; will not get app instance id
2022-12-07 16:07:23.888   833-833   AppLovinSdk             fate.facefilter.palmistry            D  [AppLovinMAX] Initializing AppLovin MAX Flutter v2.3.1...
2022-12-07 16:07:23.903   833-833   AppLovinSdk             fate.facefilter.palmistry            D  [AppLovinSdk] 
                                                                                                    ========================================
                                                                                                    SDK Session Begin
                                                                                                    ========================================
2022-12-07 16:07:23.955   833-833   AppLovinSdk             fate.facefilter.palmistry            D  [AppLovinSdk] Setting plugin version: Flutter-2.3.1
2022-12-07 16:07:26.971   833-1081  AppLovinSdk             fate.facefilter.palmistry            D  [AppLovinSdk] 
                                                                                                    ========================================
                                                                                                    =====AppLovin SDK=====
                                                                                                    ===SDK Versions===
                                                                                                    Version: 11.6.0
                                                                                                    Plugin Version: Flutter-2.3.1
                                                                                                    Ad Review Version: 
                                                                                                    OM SDK Version: 1.4.1-Applovin
                                                                                                    ===Device Info===
                                                                                                    OS: 10 (Q - API 29)
                                                                                                    GAID: <Enable verbose logging to see the GAID to use for test devices - https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK>
                                                                                                    Model: Pixel 3 XL
                                                                                                    Locale: zh_CN_#Hans
                                                                                                    Emulator: false
                                                                                                    Tablet: false
                                                                                                    ===App Info===
                                                                                                    Application ID: fate.facefilter.palmistry
                                                                                                    Target SDK: 31
                                                                                                    ExoPlayer Version: 2015001
                                                                                                    ===SDK Settings===
                                                                                                    SDK Key: Ehm2XimbDDeeE4URXGM6zhJ19ON5Pzt4b9a3eLLwsvFtLcyuQeciyfQ76amrDwebOSDmWT727gzBnO8Sufi2sJ
                                                                                                    Mediation Provider: max
                                                                                                    TG: 70
                                                                                                    AEI: 88
                                                                                                    MEI: 1
                                                                                                    Test Mode On: false
                                                                                                    Verbose Logging On: false
                                                                                                    ===Privacy States===
                                                                                                    Please review AppLovin MAX documentation to be compliant with regional privacy policies.
                                                                                                    
                                                                                                    Age Restricted User - No value set
                                                                                                    Has User Consent - No value set
                                                                                                    "Do Not Sell" - No value set
                                                                                                    ========================================
2022-12-07 16:07:26.987   833-833   AppLovinSdk             fate.facefilter.palmistry            D  [AppLovinMAX] SDK initialized
2022-12-07 16:07:27.969   833-911   Gralloc3                fate.facefilter.palmistry            W  mapper 3.x is not supported
2022-12-07 16:07:27.969   833-833   1.raster                fate.facefilter.palmistry            W  type=1400 audit(0.0:32328): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=25893 scontext=u:r:untrusted_app:s0:c88,c263,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2022-12-07 16:07:27.972   833-911   libc                    fate.facefilter.palmistry            E  Access denied finding property "vendor.gralloc.disable_ahardware_buffer"
2022-12-07 16:07:28.422   833-1116  AppLovinSdk             fate.facefilter.palmistry            D  [MediationDebuggerListAdapter] 
                                                                                                    ========== MEDIATION DEBUGGER ==========
                                                                                                    ========== APP INFO ==========
                                                                                                    Dev Build - true
                                                                                                    Test Mode - disabled
                                                                                                    Target SDK - 31
                                                                                                    ========== MAX ==========
                                                                                                    SDK Version - 11.6.0
                                                                                                    Plugin Version - Flutter-2.3.1
                                                                                                    Ad Review Version - Disabled
                                                                                                    ========== PRIVACY ==========
                                                                                                    Age Restricted User - No value set
                                                                                                    Has User Consent - No value set
                                                                                                    "Do Not Sell" - No value set
                                                                                                    ========== NETWORKS ==========
                                                                                                    ---------- APPLOVIN_NETWORK ----------
                                                                                                    Status  - COMPLETE
                                                                                                    SDK     - 11.6.0
                                                                                                    Adapter - 11.6.0
                                                                                                    ---------- GOOGLE_AD_MANAGER_NETWORK ----------
                                                                                                    Status  - INCOMPLETE INTEGRATION
                                                                                                    SDK     - UNAVAILABLE
                                                                                                    Adapter - UNAVAILABLE
                                                                                                    ---------- ADMOB_NETWORK ----------
                                                                                                    Status  - INCOMPLETE INTEGRATION
                                                                                                    SDK     - UNAVAILABLE
                                                                                                    Adapter - UNAVAILABLE
                                                                                                    ========== AD UNITS ==========
                                                                                                    ---------- banner ----------
                                                                                                    Identifier - 0e5db2223983279d
                                                                                                    Format     - BANNER
                                                                                                    ---------- int ----------
                                                                                                    Identifier - 46fe756b433568d6
                                                                                                    Format     - INTER
                                                                                                    ---------- int_high ----------
                                                                                                    Identifier - e8c76e174080b851
                                                                                                    Format     - INTER
2022-12-07 16:07:28.423   833-1116  AppLovinSdk             fate.facefilter.palmistry            D  [MediationDebuggerListAdapter] 
                                                                                                    
                                                                                                    ---------- int_medium ----------
                                                                                                    Identifier - 210e2c8d085c3c5c
                                                                                                    Format     - INTER
                                                                                                    ---------- int_splash ----------
                                                                                                    Identifier - 704e9d9eff71f417
                                                                                                    Format     - INTER
                                                                                                    ---------- MREC ----------
                                                                                                    Identifier - 78e988abd12783ea
                                                                                                    Format     - MREC
                                                                                                    ---------- native ----------
                                                                                                    Identifier - 1e5b327761c595bc
                                                                                                    Format     - NATIVE
                                                                                                    ---------- OPEN ----------
                                                                                                    Identifier - d675b45dc8e85594
                                                                                                    Format     - APPOPEN
                                                                                                    ---------- OPEN2 ----------
                                                                                                    Identifier - 695eb8aa9b73b6b8
                                                                                                    Format     - APPOPEN
                                                                                                    ---------- open_resume ----------
                                                                                                    Identifier - 9d6b8842bec0c2a6
                                                                                                    Format     - APPOPEN
                                                                                                    ---------- vdo ----------
                                                                                                    Identifier - 137a21f2104988bb
                                                                                                    Format     - REWARDED
                                                                                                    ========== END ==========
2022-12-07 16:07:40.902   833-871   ilter.palmistr          fate.facefilter.palmistry            I  Background concurrent copying GC freed 1943(1713KB) AllocSpace objects, 26(21MB) LOS objects, 49% free, 11MB/23MB, paused 5.994ms total 43.149ms
2022-12-07 16:07:51.892   833-833   AppLovinSdk             fate.facefilter.palmistry            D  [MaxInterstitialAd] Created new MaxInterstitialAd (MaxInterstitialAd{adUnitId='46fe756b433568d6', adListener=null, revenueListener=null, requestListenernull, adReviewListenernull, isReady=false})

```

This is futter doctor info : 
```
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.4 21F79 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.4 on channel stable at /Users/haianhsing/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (9 周前), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/haianhsing/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/haianhsing/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 3 XL (mobile) • FLHG65002578010J8C30060H • android-arm64  • Android 10 (API 29)
    • macOS (desktop)     • macos                    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)        • chrome                   • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

Before load ad, I disconnect my network, a log with 'onAdDisplayFailedCallback: $ad, $error' is expected but nothing after 5minutes.

> "ad load failure" is that callback. If you enable and send over the verbose logs we can check it out.

**Comment by alhiwatan** [comment]
@haianhsing, `onAdLoadFailedCallback` will be fired for the loading error.    This is my error from [our demo app](https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/043b04b5a9e188fe6854aa677943505086b78892/applovin_max/example/lib/main.dart#L119) when disconnecting the network before loading.

`I/flutter ( 6599): Interstitial ad failed to load with code -1009 - retrying in 4s
`

**Comment by haianhsing** [comment]
> @haianhsing, `onAdLoadFailedCallback` will be fired for the loading error. This is my error from [our demo app](https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/043b04b5a9e188fe6854aa677943505086b78892/applovin_max/example/lib/main.dart#L119) when disconnecting the network before loading.
> 
> `I/flutter ( 6599): Interstitial ad failed to load with code -1009 - retrying in 4s `

I try it on 2.3.2, it has no problem. Thanks!
