### ISSUE TITLE
can't create MaxAdView widget

### ISSUE THREAD

**Issue by amondnet** [AppLovin/AppLovin-MAX-Flutter#76]
### MAX Plugin Version

2.4.0

### Flutter Version

3.7.3

### Device/Platform Info

Android

### Current Behavior

can't create MaxAdView widget

### Expected Behavior

create MaxAdView widget

### How to Reproduce

```dart
returnMaxAdView(
  adFormat: AdFormat.mrec,
  adUnitId: 'xxxxxxxxxxxx',
);
```

### Additional Info

https://github.com/AppLovin/AppLovin-MAX-Flutter/blob/940e2f6b47f31c2586497fa7473655fe38a57d63/applovin_max/android/src/main/java/com/applovin/applovin_max/AppLovinMAXAdViewFactory.java#L53

```
D/AppLovinSdk( 8985): [AppLovinMAX] Creating MaxAdView widget with Ad Unit ID: xxxxxxxxxxx
E/MethodChannel#flutter/platform_views( 8985): Failed to handle method call
E/MethodChannel#flutter/platform_views( 8985): java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
E/MethodChannel#flutter/platform_views( 8985): 	at com.applovin.applovin_max.AppLovinMAXAdViewFactory.create(AppLovinMAXAdViewFactory.java:53)
E/MethodChannel#flutter/platform_views( 8985): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:503)
E/MethodChannel#flutter/platform_views( 8985): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:191)
E/MethodChannel#flutter/platform_views( 8985): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/MethodChannel#flutter/platform_views( 8985): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views( 8985): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter/platform_views( 8985): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views( 8985): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter/platform_views( 8985): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$2j2MERcK825A5j1fv5sZ7xB2Iuo.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views( 8985): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#flutter/platform_views( 8985): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views( 8985): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter/platform_views( 8985): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter/platform_views( 8985): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/MethodChannel#flutter/platform_views( 8985): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 8985): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter/platform_views( 8985): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by thomasmso** [comment]
Fixed in v2.4.1.
