### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by fingerart** [AppLovin/AppLovin-MAX-Flutter#84]
### MAX Plugin Version

2.3.2

### Flutter Version

3.3.10

### Device/Platform Info

Android 10, Galaxy A11

### Current Behavior

-

### How to Reproduce

-

### Additional Info

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ai.polyverse.mirror/com.applovin.creative.MaxCreativeDebuggerDisplayedAdActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.applovin.impl.a.a.a.a.a()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8107)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.applovin.impl.a.a.a.a.a()' on a null object reference
       at com.applovin.impl.a.a.b.a.c.onCreate(SourceFile:45)
       at android.app.Activity.performCreate(Activity.java:7957)
       at android.app.Activity.performCreate(Activity.java:7946)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8107)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by thomasmso** [comment]
This has been fixed in v11.7.0 of our native Android SDK, which is a dependency of Flutter v2.4.1 and above.
